[package]
name = "crypto_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
init_lib = { path="../../src/init_lib" }
rsa = "0.4.0"