name: Check

on:
  workflow_dispatch:
    inputs:
      job:
        required: true
        default: 'check'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check
